---
title: "Mapping EJ in Utica"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(mapview)
library(raster)
library(sf)



```




```{r echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
noiseCrop <- raster("/Volumes/GoogleDrive/My Drive/GIS_teaching/ENVST110_F22/noise_2018.tif")
redline <- st_read("/Volumes/GoogleDrive/My Drive/GIS_teaching/ENVST110_F22/NYUtica1936/cartodb-query.shp")
map50 <- raster("/Volumes/GoogleDrive/My Drive/GIS_teaching/ENVST110_F22/images50.tif")
tempAnom <- raster("/Volumes/GoogleDrive/My Drive/GIS_teaching/ENVST110_F22/temp_anom_c.tif")

Ucenter2 <- extent(-8382000,-8373500,
                   5324000,5329000)

map50c <- crop(map50, Ucenter2)
map50r <- projectRaster(map50c, crs="+init=epsg:4326")
tempAnomr <- projectRaster(tempAnom, crs="+init=epsg:4326")
```
map50t <- projectRaster(map50c, crs=st_crs(redline))
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=}
mapview(noiseCrop, layer.name = "noise (dB)")+
  mapview(tempAnomr, col=hcl.colors(12,"Zissou1") )+
  mapview(map50r, col=grey(1:100/100), maxpixels=5000000, alpha=1)+
  mapview(redline)#["holc_grade"], col.regions=c("palegreen4",
                                              # "royalblue3",
                                               #"darkgoldenrod2",
                                               #"tomato3"), layer.name="redlining grade")


mapview(map50, col=grey(1:100/100),  alpha=1)
```